### ISSUE TITLE
CvException (-215) u != 0 in function void cv::Mat::create

### ISSUE THREAD

**Issue by mus0007** [DanielBeato/GESPRO_PracticaGestionTareas_1718#47]
La app corre bien durante unos minutos hasta que de repente salta la siguiente excepción:
```
10-23 03:11:01.383 29890-30641/com.davidmiguel.gobees E/AndroidRuntime: FATAL EXCEPTION: Thread-8061
                                                                        Process: com.davidmiguel.gobees, PID: 29890
                                                                        CvException [org.opencv.core.CvException: cv::Exception: /Volumes/Linux/builds/master_pack-android/opencv/modules/core/src/matrix.cpp:424: error: (-215) u != 0 in function void cv::Mat::create(int, const int*, int)
                                                                        ]
                                                                            at org.opencv.core.Mat.n_Mat(Native Method)
                                                                            at org.opencv.core.Mat.<init>(Mat.java:37)
                                                                            at com.davidmiguel.gobees.video.processors.ContoursFinder.process(ContoursFinder.java:68)
                                                                            at com.davidmiguel.gobees.video.ContourBeesCounter.countBees(ContourBeesCounter.java:61)
                                                                            at com.davidmiguel.gobees.MainActivity.onCameraFrame(MainActivity.java:96)
                                                                            at org.opencv.android.CameraBridgeViewBase.deliverAndDrawFrame(CameraBridgeViewBase.java:391)
                                                                            at org.opencv.android.JavaCameraView$CameraWorker.run(JavaCameraView.java:350)
                                                                            at java.lang.Thread.run(Thread.java:818)
```

**Comment by mus0007** [comment]
El error tarda en saltar unos 5-6 minutos y se produce en la siguiente [línea del código nativo](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix.cpp#L426):

`u = a->allocate(dims, size, _type, 0, step.p, 0, USAGE_DEFAULT);`

**Comment by mus0007** [comment]
Efectivamente:
`10-23 13:25:14.370 21560-21847/com.davidmiguel.gobees E/cv::error(): OpenCV Error: Insufficient memory (Failed to allocate 921600 bytes) in void* cv::OutOfMemoryError(size_t), file /Volumes/Linux/builds/master_pack-android/opencv/modules/core/src/alloc.cpp, line 52`

**Comment by mus0007** [comment]
Resuelto. El problema residía en que OpenCV no libera correctamente la matriz devuelta en el método onCameraFrame(), y por lo tanto hay que hacerlo explícitamente.

Explico como actuar correctamente en esta [respuesta en StackOverflow](https://stackoverflow.com/questions/40203327/is-recommended-to-release-cvcameraviewframe-inputframe/40203578#40203578).

**Comment by jorgenavarroglez** [comment]
muy bien mario cruck!

**Comment by DanielBeato** [comment]
Sigue Mario SIGUE!!!!!!!!!!!! Vas muy bien!

**Comment by jorgenavarroglez** [comment]
Yo creo que lo tienes ya arreglado eh, buen trabajo, y parecía tonto cuando lo compramos!
